package lk.ac.ucsc.oms.scheduler.api;

/**
 * User: Ruchira Ranaweera
 * Date: 1/24/14
 */
public enum CronSchedulerName {
    BUY_TPLUS_REMOVE_SCHEDULER, DISABLE_DAILY_OD_LIMIT_SCHEDULER, REMOVE_EXPIRED_SYMBOL_SCHEDULER, UPDATED_DAY_MARGIN_SCHEDULER,
    UPDATE_USED_DAY_TRADING_LIMIT_SCHEDULER, UPDATE_SUSPENDED_STATUS_SCHEDULER, FOL_ORDER_EXPIRE_SCHEDULER, AUXILIARY_UPDATE_SCHEDULER,
    CLEAN_ACTIVE_SYMBOL_SCHEDULER, REMOVE_DAY_MARGIN_DUE_AND_DAY_HOLDING_AT_MKT_CLOSE_SCHEDULER, UPDATE_PENDING_SETTLE_SCHEDULER,
    RESET_PRICEDATA_CACHE_LOADED_STATUS, REFRESH_MARGINABLE_SYMBOL_LIST, CLEAN_HISTORY_TABLE_DATA

}
