package lk.ac.ucsc.oms.messaging_protocol_json.api;


public interface MessageConstants {

    int GROUP_TRADING = GroupConstants.GROUP_TRADING;

    int REQUEST_TYPE_NEW_NORMAL_ORDER = 1;
    int REQUEST_TYPE_AMEND_NORMAL_ORDER = 7;
    int REQUEST_TYPE_CANCEL_NORMAL_ORDER = 12;
    int REQUEST_TYPE_EXPIRE_ORDER = 20;


    int RESPONSE_TYPE_NEW_NORMAL_ORDER = 101;
    // --->
    // <-- TRADING INQUIRY GROUP
    int GROUP_TRADING_INQUIRY = GroupConstants.GROUP_TRADING_INQUIRY;
    int REQUEST_TYPE_ORDER_SEARCH = 1;
    int REQUEST_TYPE_ORDER_DETAILS = 2;
    int REQUEST_TYPE_ORDER_LIST = 3;

    int RESPONSE_TYPE_ORDER_SEARCH = 101;
    int RESPONSE_TYPE_ORDER_DETAILS = 102;
    int RESPONSE_TYPE_ORDER_LIST = 103;
    // -->
    // <-- INQUIRY GROUP
    int GROUP_INQUIRY = GroupConstants.GROUP_INQUIRY;
    int REQUEST_TYPE_BUYING_POWER = 1;
    int REQUEST_TYPE_PORTFOLIO = 2;

    int RESPONSE_TYPE_BUYING_POWER = 101;
    int RESPONSE_TYPE_PORTFOLIO = 102;


    int RESPONSE_TYPE_BUYING_POWER_UNSOLICITED = 201;
    int RESPONSE_TYPE_ALERT =202;


    // -->
    // <-- AUTHENTICATION GROUP
    int GROUP_AUTHENTICATION = GroupConstants.GROUP_AUTHENTICATION;

    int REQUEST_TYPE_AUTH_NORMAL = 1;
    int REQUEST_TYPE_CHANG_PWD = 3;
    int REQUEST_TYPE_LOGOUT = 4;
    int RESPONSE_TYPE_AUTH_NORMAL = 101;
    int RESPONSE_TYPE_CHANG_PWD = 103;
    int RESPONSE_TYPE_LOGOUT = 104;

    // -->
    // <-- CUSTOMER INQUIRIES GROUP
    int GROUP_CUSTOMER_INQUIRY = GroupConstants.GROUP_CUSTOMER_INQUIRY;
    int REQUEST_TYPE_CUSTOMER_DETAIL = 1;
    int REQUEST_TYPE_CUSTOMER_ACCOUNT_DETAIL = 3;
    int REQUEST_TYPE_CUSTOMER_LIST_BY_USER = 5;

    int RESPONSE_TYPE_CUSTOMER_DETAIL = 101;
    int RESPONSE_TYPE_CUSTOMER_ACCOUNT_DETAIL = 103;
    int RESPONSE_TYPE_CUSTOMER_LIST_BY_USER = 105;

    int GROUP_SYSTEM = GroupConstants.GROUP_SYSTEM;
    int REQUEST_TYPE_PULSE = 1;
    int RESPONSE_TYPE_PULSE = 101;

    int GROUP_ERROR_MESSAGES = GroupConstants.GROUP_ERROR_MESSAGES;

    int RESPONSE_TYPE_ERROR_CONNECTION = 101;
    int RESPONSE_TYPE_ERROR_SYSTEM = 102;
    int RESPONSE_TYPE_ERROR_INVALID_SESSION = 103;
    int RESPONSE_TYPE_ERROR_INVALID_REQUEST = 104;


}
